spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 17060220Aa@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.MySQLDialect
      show-sql: false
    open-in-view: false